<script>
	import Text from '$lib/components/Text/Text.svelte';
	import Helpful from '$lib/pages/PrivacyPolicyPage/components/Helpful/Helpful.svelte';

	const terms = [
		{
			term: 'Cookie',
			definition:
				'Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.'
		},
		{
			term: 'Company',
			definition:
				'When this policy mentions “Company,” “we,” “us,” or “our,” it refers to Luxehouze SG PTE LTD, that is responsible for your information under this Privacy Policy.'
		},
		{
			term: 'Country',
			definition:
				'Where Luxehouze or the owners/founders of Luxehouze are based, in this case is Singapore.'
		},
		{
			term: 'Customer',
			definition:
				'Refers to the company, organization, or person that signs up to use the Luxehouze Service to manage the relationships with your consumers or service users.'
		},
		{
			term: 'Device',
			definition:
				'Any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit Luxehouze and use the services.'
		},
		{
			term: 'IP address',
			definition:
				'Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.'
		},
		{
			term: 'Personnel',
			definition:
				'Refers to those individuals who are employed by Luxehouze or are under contract to perform a service on behalf of one of the parties.'
		},
		{
			term: 'Personal Data',
			definition:
				'Any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.'
		},
		{
			term: 'Service',
			definition:
				'Refers to the service provided by Luxehouze as described in the relative terms (if available) and on this platform.'
		},
		{
			term: 'Third-party service',
			definition:
				'Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.'
		},
		{
			term: 'Website',
			definition: "Luxehouze's site, which can be accessed via this URL: www.luxehouze.com"
		},
		{
			term: 'You',
			definition: 'A person or entity that is registered with Luxehouze to use the Services.'
		}
	];
</script>

<div class="container max-w-[1600px] md:p-16 p-4">
	<Text type="subtitle-1" color="black-9" weight="semibold">Privacy Policy</Text>
	<div class="grid mt-4">
		<Text type="body-2" weight="semibold">Last Updated: 18 August 2022</Text>
		<Text type="body-2" class="mt-4">
			Luxehouze (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy
			explains how your personal information is collected, used, and disclosed by Luxehouze. This
			Privacy Policy applies to our website, and its associated subdomains (collectively, our
			“Service”) alongside our application, Luxehouze. By accessing or using our Service, you
			signify that you have read, understood, and agree to our collection, storage, use, and
			disclosure of your personal information as described in this Privacy Policy and our Terms of
			Service.
		</Text>
		<Text type="body-2" weight="semibold" class="mt-4">Definitions and key terms</Text>
		<Text type="body-2" class="mb-4">
			To help explain things as clearly as possible in this Privacy Policy, every time any of these
			terms are referenced, they are strictly defined as:
		</Text>
		<ul class="list-disc pl-6 mb-4 space-y-2">
			{#each terms as { term, definition }}
				<li>
					<Text type="body-2">
						<strong>{term}:</strong>
						{definition}
					</Text>
				</li>
			{/each}
		</ul>
	</div>
	<Helpful />
</div>
