export const ErrorCodes = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
    INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
    PASSWORD_NOT_EXISTS: 'PASSWORD_NOT_EXISTS',
    PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
    USER_EMAIL_NOT_FOUND: 'USER_EMAIL_NOT_FOUND',
    // SHOPIFY_HANDLING_ERROR: 'SHOPIFY_HANDLING_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    FIRST_NAME_NOT_EXISTS: 'FIRST_NAME_NOT_EXISTS',
    LAST_NAME_NOT_EXISTS: 'LAST_NAME_NOT_EXISTS',
    PHONE_NUMBER_NOT_EXISTS: 'PHONE_NUMBER_NOT_EXISTS',
    INVALID_PHONE_NUMBER_FORMAT: 'INVALID_PHONE_NUMBER_FORMAT',
    MISMATCH_COUNTRY_CODE: 'MISMATCH_COUNTRY_CODE',
    CONFIRM_PASSWORD_NOT_EXISTS: 'CONFIRM_PASSWORD_NOT_EXISTS',
    MISMATCH_CONFIRM_PASSWORD: 'MISMATCH_CONFIRM_PASSWORD',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    PHONE_NUMBER_ALREADY_EXISTS: 'PHONE_NUMBER_ALREADY_EXISTS',
}

export const ErrorMessages = {
    DefaultRequestValidation: "Error when validating request",
    EmailNotExists: "Email cannot be empty",
    InvalidEmailFormat: "Invalid email format",
    PasswordNotExists: "Password cannot be empty",
    InvalidPasswordFormat: "Invalid password format",
    PasswordMismatch: "Incorrect email and password combination",
    UnexpectedError: "An unexpected error occurred. Please try again later",
    EmailNotFound: "Email not found",
    FirstNameRequired: "First name cannot be empty",
    LastNameRequired: "Last name cannot be empty",
    PhoneNumberRequired: "Phone number cannot be empty",
    InvalidPhoneFormat: "Invalid phone number format",
    MismatchCountryCode: "Country code does not match the selected store",
    ConfirmPasswordRequired: "Confirm password cannot be empty",
    MismatchConfirmPassword: "Password does not match",
    EmailAlreadyRegistered: "Email already registered",
    PhoneAlreadyRegistered: "Phone number already registered"
}