//abtest
export type TextColor =
  | 'brown-1'
  | 'brown-2'
  | 'brown-3'
  | 'brown-4'
  | 'brown-5'
  | 'brown-6'
  | 'brown-7'
  | 'brown-8'
  | 'brown-9'
  | 'brown-10'
  | 'brown-05'
  | 'dark-brown-1'
  | 'dark-brown-2'
  | 'dark-brown-3'
  | 'dark-brown-4'
  | 'dark-brown-5'
  | 'dark-brown-6'
  | 'dark-brown-7'
  | 'dark-brown-8'
  | 'dark-brown-9'
  | 'dark-brown-10'
  | 'beige-1'
  | 'beige-2'
  | 'beige-3'
  | 'beige-4'
  | 'beige-5'
  | 'beige-6'
  | 'beige-7'
  | 'beige-8'
  | 'beige-9'
  | 'beige-10'
  | 'red-1'
  | 'red-2'
  | 'red-3'
  | 'red-4'
  | 'red-5'
  | 'red-6'
  | 'red-7'
  | 'red-8'
  | 'red-9'
  | 'red-10'
  | 'blue-1'
  | 'blue-2'
  | 'blue-3'
  | 'blue-4'
  | 'blue-5'
  | 'blue-6'
  | 'blue-7'
  | 'blue-8'
  | 'blue-9'
  | 'blue-10'
  | 'green-1'
  | 'green-2'
  | 'green-3'
  | 'green-4'
  | 'green-5'
  | 'green-6'
  | 'green-7'
  | 'green-8'
  | 'green-9'
  | 'green-10'
  | 'black-1'
  | 'black-2'
  | 'black-3'
  | 'black-4'
  | 'black-5'
  | 'black-6'
  | 'black-7'
  | 'black-8'
  | 'black-9'
  | 'black-10'
  | 'white-1'
  | 'white-2'
  | 'green-whatsapp'
  ;

export type TextType =
  | 'title-1'
  | 'title-2'
  | 'title-3'
  | 'subtitle-1'
  | 'subtitle-2'
  | 'subtitle-3'
  | 'body-1'
  | 'body-2'
  | 'caption-1'
  | 'caption-2';

  export type TextVariant =
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'h5'
  | 'h6'
  | 'span'



export type TextWeight = 'regular' | 'medium' | 'semibold' | 'bold';
